export const BIKE_STATUS = {
  AVAILABLE: 'AVAILABLE',
  RENTED: 'RENTED',
  MAINTENANCE: 'MAINTENANCE',
};

export const BOOKING_STATUS = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PENDING: 'PENDING',
  CANCELLED: 'CANCELLED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
};

export const EXCLUDE_BOOKING_STATUS = [BOOKING_STATUS.COMPLETED, BOOKING_STATUS.CANCELLED];

export const ACCEPT_BOOKING_STATUS = [BOOKING_STATUS.APPROVED, BOOKING_STATUS.ACTIVE, BOOKING_STATUS.PENDING];

export const NOTIFICATION_TYPE = {
  RENTAL_REQUEST: 'rental_request',
  RENTAL_ACCEPTED: 'rental_accepted',
  RENTAL_REJECTED: 'rental_rejected',
  RENTAL_CANCELLED: 'rental_cancelled',
  RENTAL_COMPLETED: 'rental_completed',
  RENTAL_ACTIVE: 'rental_active',
};

