export const PAYMENT_STATUS = {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    CANCELLED: 'CANCELLED',
    REFUNDED: 'REFUNDED',
    REFUND_FAILED: 'REFUND_FAILED',
    REFUND_PENDING: 'REFUND_PENDING',
    REFUND_COMPLETED: 'REFUND_COMPLETED'
}

export const PAYMENT_METHOD = {
    STRIPE: 'STRIPE',
    PAYPAL: 'PAYPAL',
    PAYSTACK: 'PAYSTACK',
    PAYMENT_GATEWAY: 'PAYMENT_GATEWAY',
}

