const OWNER_NOTIFICATION_EVENT = "owner:notification";
const OWNER_SUBSCRIBE_EVENT = "owner:subscribe";
const OWNER_UNSUBSCRIBE_EVENT = "owner:unsubscribe";
const RENTER_NOTIFICATION_EVENT = "renter:notification";
const RENTER_SUBSCRIBE_EVENT = "renter:subscribe";
const RENTER_UNSUBSCRIBE_EVENT = "renter:unsubscribe";

export { OWNER_NOTIFICATION_EVENT, OWNER_SUBSCRIBE_EVENT, OWNER_UNSUBSCRIBE_EVENT, RENTER_NOTIFICATION_EVENT, RENTER_SUBSCRIBE_EVENT, RENTER_UNSUBSCRIBE_EVENT };